export const browseMusic = {
    GET_ALL_MUSIC_SUCCESS: "GET_ALL_MUSIC_SUCCESS",
    UPDATE_STATUS_SUCCESS: "UPDATE_STATUS_SUCCESS",
    ADD_TO_PLAYLIST: "ADD_TO_PLAYLIST",
    MUSIC_CATEGORIES: "MUSIC_CATEGORIES",
    SFX_CATEGORIES: "SFX_CATEGORIES",
    SAVE_SELECTED_ROWS: "SAVE_SELECTED_ROWS",
    SELECTED_CATEGORIES: "SELECTED_CATEGORIES",
    REMOVE_SELECTED_CATEGORIES: "REMOVE_SELECTED_CATEGORIES",
    CAT_SLIDER: "CAT_SLIDER",
    CLEAR_SELECTED_CATEGORIES: "CLEAR_SELECTED_CATEGORIES",
    SELECTED_KEYWORDS: "SELECTED_KEYWORDS",
    SELECTED_SUGGETION: "SELECTED_SUGGETION",
    SELECTED_PARENT_CATS: "SELECTED_PARENT_CATS",
    UPDATE_AUDIO: "UPDATE_AUDIO",
    UPDATE_ALTERNATE_AUDIO_VERSION: "UPDATE_ALTERNATE_AUDIO_VERSION",
    ADD_TO_BLOG: "ADD_TO_BLOG",
  };
  